#!/bin/sh
#
# This script users synctree to copy the sipb cell copy of the sipb locker
# to the athena cell copy
#
# based on the original script by Derek Atkins <warlord@mit.edu>
# 
# rewritten in sh to save us all by Garry Zacheiss <zacheiss@mit.edu>
#
# $Id$
#
# $Log$
# Revision 1.3  2012/12/14 11:28:44  mitchb
# Stop using krb4.
#
# Revision 1.2  2011/12/23 19:49:27  mitchb
# Uncommitted change from forever ago to exclude "aborted prematurely"
# from synctree errors
#
#

# define some variables it might be neat to have
KRB5CCNAME=/tmp/krb5cc_sync

fromcell=sipb.mit.edu
fromdir=project/sipb
frompath=/afs/.${fromcell}/${fromdir}
fromvol=`echo $fromdir | sed -e 's/\//\./'`

tocell=athena.mit.edu
todir=contrib/sipb
topath=/afs/.${tocell}/${todir}

errs=/tmp/syncerr.$$
header=/tmp/syncheader.$$

host=`/bin/hostname`
mailto=sipb-afsreq@mit.edu
mailrepl=sipb-afsreq@mit.edu

synctree=/usr/athena/etc/synctree

vos=/usr/afs/bin/vos

# get tickets and authenticate to both cells
/usr/athena/bin/kinit -5 -k
/bin/athena/aklog $tocell $fromcell

# do the actual work
$synctree -q -nosrcrules -nodstrules -s $frompath -d $topath -a $frompath/.rconf 2>&1 | \
    egrep -v 'Parsing|Fixing|chown.*failed|chown|chmod|aborted prematurely' >>$errs

# send mail if we've had any errors we care about
if [ -s $errs ]; then
    cat > $header <<EOF
From: root@${host}
To: $mailto
Reply-To: $mailrepl
Subject: $fromcell to $tocell synctree errors

EOF

    (cat $header; cat $errs) | /usr/lib/sendmail -t -f${mailrepl}
else 
    rm -f $errs
fi

# release the sipb cell volume 
$vos release $fromvol -cell $fromcell -localauth >/dev/null 2>&1

#clean up
/bin/athena/unlog $fromcell $tocell
/usr/athena/bin/kdestroy >/dev/null 2>&1
 
exit 0

