#!/bin/sh
#
# This script users synctree to copy the sipb cell copy of the sipb locker
# to the athena cell copy
#
# based on the original script by Derek Atkins <warlord@mit.edu>
# 
# rewritten in sh to save us all by Garry Zacheiss <zacheiss@mit.edu>
#
# $Id$
#
# $Log$
# Revision 1.8  2013/10/25 19:48:37  kaduk
# Just set fromvol directly, don't bother with a funky sed-in-backticks.
# This fixes the release to the RO copies in the SIPB cell, which has
# been broken for some months.
#
# Revision 1.7  2013/07/22 04:17:53  kaduk
# Attempt to appease the rsync gods with carefully placed slashes
#
# Revision 1.6  2013/07/22 03:25:06  kaduk
# rsync appears to actually respect it's "quiet" argument; skip the
# egrep step of the pipeline.
#
# Revision 1.5  2013/07/22 03:21:07  kaduk
# More better rsync flags
#
# Revision 1.4  2013/07/22 03:13:26  kaduk
# First crack at synclocker for a debian reynelda
#
# Revision 1.3  2012/12/14 11:28:44  mitchb
# Stop using krb4.
#
# Revision 1.2  2011/12/23 19:49:27  mitchb
# Uncommitted change from forever ago to exclude "aborted prematurely"
# from synctree errors
#
#

# define some variables it might be neat to have
KRB5CCNAME=/tmp/krb5cc_sync

fromcell=sipb.mit.edu
fromdir=project/sipb/
frompath=/afs/.${fromcell}/${fromdir}
fromvol=project.sipb

tocell=athena.mit.edu
todir=contrib/sipb
topath=/afs/.${tocell}/${todir}

errs=/tmp/syncerr.$$
header=/tmp/syncheader.$$

host=`/bin/hostname`
mailto=sipb-afsreq@mit.edu
mailrepl=sipb-afsreq@mit.edu

synctree=/usr/bin/rsync

vos=/usr/bin/vos

# get tickets and authenticate to both cells
/usr/bin/kinit -5 -k host/reynelda.mit.edu
/usr/bin/aklog $tocell $fromcell

# do the actual work
$synctree -qWrp --exclude-from=$frompath/.ignore --delete $frompath $topath 2>&1 >>$errs

# send mail if we've had any errors we care about
if [ -s $errs ]; then
    cat > $header <<EOF
From: root@${host}
To: $mailto
Reply-To: $mailrepl
Subject: $fromcell to $tocell synctree errors

EOF

    (cat $header; cat $errs) | /usr/lib/sendmail -t -f${mailrepl}
else 
    rm -f $errs
fi

# release the sipb cell volume 
$vos release $fromvol -cell $fromcell -localauth >/dev/null 2>&1

#clean up
/usr/bin/unlog $fromcell $tocell
/usr/bin/kdestroy >/dev/null 2>&1
 
exit 0

